# Generated by Django 5.0.3 on 2024-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default=1, upload_to='media/students/'),
            preserve_default=False,
        ),
    ]
